### ISSUE TITLE
multiple conformation RESP calculation returns validation error

### ISSUE THREAD

**Issue by zd9999cs** [lilyminium/psiresp#106]
I am testing psiresp to perform RESP calculation on a molecule with autogenerated conformatons, on a local qcfractal server. If I disable the conformer generation and do single conformation calculation, psiresp runs well. However, when there's multiple conformers, the program raises validation error for ProcedureGETBody.

**Expected behavior**

I am expecting psiRESP to end normally.

**Actual behavior**

```
(psiresp) ombrekala@ombrekala-B760-VH5:~/psiresp4$ /home/ombrekala/mambaforge/envs/psiresp/bin/python /home/ombrekala/psiresp4/resp_calc_multi.py
/home/ombrekala/mambaforge/envs/psiresp/lib/python3.9/site-packages/psiresp/charge.py:282: FutureWarning: `symmetric_atoms_are_equivalent` will be set to False by default for now, as it is a new feature. It will be set to True by default in the future
  warnings.warn(
/home/ombrekala/mambaforge/envs/psiresp/lib/python3.9/site-packages/psiresp/charge.py:282: FutureWarning: `symmetric_atoms_are_equivalent` will be set to False by default for now, as it is a new feature. It will be set to True by default in the future
  warnings.warn(
generate-conformers: 100%|████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.45s/it]
geometry-optimization:   0%|                                                                                                  | 0/2 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/ombrekala/mambaforge/envs/psiresp/lib//python3.9/site-packages/qcfractal/interface/client.py", line 270, in _automodel_request
    payload = body_model(**payload)
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for ProcedureGETBody
data -> id -> 0
  none is not an allowed value (type=type_error.none.not_allowed)
data -> id
  The string [None, '1'] is not a valid 24-character hexadecimal or integer ObjectId! (type=type_error)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ombrekala/psiresp4/resp_calc_multi.py", line 20, in <module>
    job.run(client=client,update_molecules=True)
  File "/home/ombrekala/mambaforge/envs/psiresp/lib/python3.9/site-packages/psiresp/job.py", line 218, in run
    self.optimize_geometries(client=client)
  File "/home/ombrekala/mambaforge/envs/psiresp/lib/python3.9/site-packages/psiresp/job.py", line 147, in optimize_geometries
    results = self.qm_optimization_options.run(client=client,
  File "/home/ombrekala/mambaforge/envs/psiresp/lib/python3.9/site-packages/psiresp/qm.py", line 209, in run
    records = self.add_compute_and_wait(client, qcmols=qcmols, **kwargs)
  File "/home/ombrekala/mambaforge/envs/psiresp/lib/python3.9/site-packages/psiresp/qm.py", line 179, in add_compute_and_wait
    return self.wait_for_results(client, response_ids=response.ids)
  File "/home/ombrekala/mambaforge/envs/psiresp/lib/python3.9/site-packages/psiresp/qm.py", line 427, in wait_for_results
    results = wait(client, response_ids=response_ids,
  File "/home/ombrekala/mambaforge/envs/psiresp/lib/python3.9/site-packages/psiresp/qm.py", line 467, in wait
    results = query(id=response_ids)
  File "/home/ombrekala/mambaforge/envs/psiresp/lib//python3.9/site-packages/qcfractal/interface/client.py", line 786, in query_procedures
    response = self._automodel_request("procedure", "get", payload, full_return=True)
  File "/home/ombrekala/mambaforge/envs/psiresp/lib//python3.9/site-packages/qcfractal/interface/client.py", line 272, in _automodel_request
    raise TypeError(str(exc))
TypeError: 2 validation errors for ProcedureGETBody
data -> id -> 0
  none is not an allowed value (type=type_error.none.not_allowed)
data -> id
  The string [None, '1'] is not a valid 24-character hexadecimal or integer ObjectId! (type=type_error)
geometry-optimization:   0%|                                                                                                  | 0/2 [00:20<?, ?it/s]
```

**To Reproduce**

I use following script as input

```
import psiresp
import psi4

from rdkit import Chem

dmso = psiresp.Molecule.from_smiles("CCCCO")

conformersettings = psiresp.ConformerGenerationOptions(n_conformer_pool=5000,n_max_conformers=1)
constraints = psiresp.ChargeConstraintOptions(symmetric_atoms_are_equivalent=True,split_conformers=False)

dmso.conformer_generation_options = conformersettings

dmso.optimize_geometry=True

job = psiresp.Job(molecules=[dmso],charge_constraints=constraints)

from qcfractal import interface as ptl

client = ptl.FractalClient("localhost:7777",verify=False)
job.run(client=client,update_molecules=True)

dmso = job.molecules[0]
print(dmso.charges)
```

**Computing environment:**
 - Operating system: Linux Ubuntu 23.04 
 - Python version (3.7, 3.8, 3.9?): 3.9.16
 - Version of PsiRESP: 0.4.2
 - Output of running `conda list`: 
 ```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
abseil-cpp                20220623.0           h8cdb687_6    conda-forge
alembic                   1.8.1            py39h06a4308_0    anaconda
amberlite                 16.0                     pypi_0    pypi
ambertools                20.9                     pypi_0    pypi
ambit                     0.6              py39h53dec33_2    psi4
anyio                     4.0.0              pyhd8ed1ab_0    conda-forge
argon2-cffi               23.1.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py39hb9d737c_3    conda-forge
arpack                    3.7.0                hc6cf775_2    conda-forge
arrow                     1.2.3              pyhd8ed1ab_0    conda-forge
arrow-cpp                 11.0.0           ha770c72_5_cpu    conda-forge
asttokens                 2.4.0              pyhd8ed1ab_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
async-lru                 2.0.4              pyhd8ed1ab_0    conda-forge
attrs                     22.1.0           py39h06a4308_0    anaconda
aws-c-auth                0.6.24               h84a1944_5    conda-forge
aws-c-cal                 0.5.20               hc60faf5_6    conda-forge
aws-c-common              0.8.11               h0b41bf4_0    conda-forge
aws-c-compression         0.2.16               h034cb4b_3    conda-forge
aws-c-event-stream        0.2.18               h75388cd_6    conda-forge
aws-c-http                0.7.4                hf084cc8_2    conda-forge
aws-c-io                  0.13.17              h10df833_2    conda-forge
aws-c-mqtt                0.8.6                hc41645a_6    conda-forge
aws-c-s3                  0.2.4                h1b8f470_3    conda-forge
aws-c-sdkutils            0.1.7                h034cb4b_3    conda-forge
aws-checksums             0.1.14               h034cb4b_3    conda-forge
aws-crt-cpp               0.19.7               h0073717_7    conda-forge
aws-sdk-cpp               1.10.57              h4707e7a_4    conda-forge
babel                     2.12.1             pyhd8ed1ab_1    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.5              pyhd8ed1ab_0    conda-forge
bcrypt                    3.2.0            py39h5eee18b_1    anaconda
beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
biopython                 1.81             py39h72bdee0_0    conda-forge
blas                      1.0                         mkl    anaconda
bleach                    6.0.0              pyhd8ed1ab_0    conda-forge
blosc                     1.21.3               hafa529b_0    conda-forge
bokeh                     3.2.2              pyhd8ed1ab_0    conda-forge
boost                     1.74.0           py39h5472131_5    conda-forge
boost-cpp                 1.74.0               h75c5d50_8    conda-forge
bottleneck                1.3.5            py39h7deecbd_0    anaconda
brotli                    1.0.9                h5eee18b_7    anaconda
brotli-bin                1.0.9                h5eee18b_7    anaconda
brotlipy                  0.7.0           py39h27cfd23_1003    anaconda
bzip2                     1.0.8                h7b6447c_0    anaconda
c-ares                    1.18.1               h7f8727e_0    anaconda
ca-certificates           2023.7.22            hbcca054_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachetools                5.3.1              pyhd8ed1ab_0    conda-forge
cairo                     1.16.0               h19f5f5c_2    anaconda
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py39h5eee18b_3    anaconda
cftime                    1.6.2            py39h2ae25f5_1    conda-forge
charset-normalizer        2.0.4              pyhd3eb1b0_0    anaconda
chemps2                   1.8.11               hbe8a562_0    psi4
click                     8.1.7           unix_pyh707e725_0    conda-forge
cloudpickle               2.2.1              pyhd8ed1ab_0    conda-forge
comm                      0.1.4              pyhd8ed1ab_0    conda-forge
contourpy                 1.0.5            py39hdb19cb5_0    anaconda
cryptography              38.0.4           py39h9ce1e76_0    anaconda
cudatoolkit               11.8.0              h4ba93d1_12    conda-forge
curl                      8.1.2                h409715c_0    conda-forge
cycler                    0.11.0             pyhd3eb1b0_0    anaconda
cython                    3.0.2            py39h3d6467e_0    conda-forge
cytoolz                   0.12.2           py39hd1e30aa_0    conda-forge
dask                      2023.9.2           pyhd8ed1ab_0    conda-forge
dask-core                 2023.9.2           pyhd8ed1ab_0    conda-forge
dask-jobqueue             0.8.2              pyhd8ed1ab_0    conda-forge
debugpy                   1.8.0            py39h3d6467e_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
dftd3                     3.2.1                h84218bc_2    psi4
distributed               2023.9.2           pyhd8ed1ab_0    conda-forge
dkh                       1.2                  h173d85e_2    psi4
double-conversion         3.1.5                he6710b0_1    anaconda
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
exceptiongroup            1.1.3              pyhd8ed1ab_0    conda-forge
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
expat                     2.4.9                h6a678d5_0    anaconda
fasteners                 0.17.3             pyhd8ed1ab_0    conda-forge
fftw                      3.3.8           nompi_hfc0cae8_1114    conda-forge
flit-core                 3.6.0              pyhd3eb1b0_0    anaconda
fontconfig                2.14.0               h8e229c2_0    conda-forge
fonttools                 4.25.0             pyhd3eb1b0_0    anaconda
fqdn                      1.5.1              pyhd8ed1ab_0    conda-forge
freetype                  2.12.1               h4a9f257_0    anaconda
fsspec                    2023.9.1           pyh1a96a4e_0    conda-forge
gau2grid                  2.0.7                hd18ef5c_0    psi4
gcp                       2.0.2                he991be0_2    psi4
gdma                      2.2.6                h0e1e685_6    psi4
geometric                 1.0                pyhd8ed1ab_1    conda-forge
gflags                    2.2.2                he6710b0_0    anaconda
giflib                    5.2.1                h5eee18b_1    anaconda
glib                      2.69.1               he621ea3_2    anaconda
glog                      0.6.0                h6f12383_0    conda-forge
griddataformats           1.0.1              pyhd8ed1ab_0    conda-forge
grpc-cpp                  1.51.1               h27aab58_1    conda-forge
gsd                       3.1.1            py39h0f8d45d_0    conda-forge
h5py                      2.10.0           py39hec9cf62_0    anaconda
hdf4                      4.2.15               h9772cbc_5    conda-forge
hdf5                      1.10.6          nompi_h3c11f04_101    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
idna                      3.4              py39h06a4308_0    anaconda
importlib-metadata        6.8.0              pyha770c72_0    conda-forge
importlib_metadata        6.8.0                hd8ed1ab_0    conda-forge
importlib_resources       5.2.0              pyhd3eb1b0_1    anaconda
iniconfig                 1.1.1              pyhd3eb1b0_0    anaconda
intel-openmp              2021.4.0          h06a4308_3561    anaconda
ipykernel                 6.25.2             pyh2140261_0    conda-forge
ipython                   8.15.0             pyh0d859eb_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.8.0              pyhd8ed1ab_0    conda-forge
isoduration               20.11.0            pyhd8ed1ab_0    conda-forge
jedi                      0.19.0             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.3.2              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h7f8727e_0    anaconda
json5                     0.9.14             pyhd8ed1ab_0    conda-forge
jsonpointer               2.4              py39hf3d152e_2    conda-forge
jsonschema                4.17.3             pyhd8ed1ab_0    conda-forge
jsonschema-with-format-nongpl 4.17.3             pyhd8ed1ab_0    conda-forge
jupyter-lsp               2.2.0              pyhd8ed1ab_0    conda-forge
jupyter_client            8.3.1              pyhd8ed1ab_0    conda-forge
jupyter_core              5.3.1            py39hf3d152e_0    conda-forge
jupyter_events            0.6.3              pyhd8ed1ab_1    conda-forge
jupyter_server            2.7.3              pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.4.4              pyhd8ed1ab_1    conda-forge
jupyterlab                4.0.6              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.24.0             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.1.7              pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.4            py39h6a678d5_0    anaconda
krb5                      1.20.1               h81ceb04_0    conda-forge
lcms2                     2.12                 h3be6417_0    anaconda
ld_impl_linux-64          2.38                 h1181459_1    anaconda
lerc                      3.0                  h295c915_0    anaconda
libabseil                 20220623.0      cxx17_h05df665_6    conda-forge
libarrow                  11.0.0           h2ebd325_5_cpu    conda-forge
libblas                   3.9.0            12_linux64_mkl    conda-forge
libbrotlicommon           1.0.9                h5eee18b_7    anaconda
libbrotlidec              1.0.9                h5eee18b_7    anaconda
libbrotlienc              1.0.9                h5eee18b_7    anaconda
libcrc32c                 1.1.2                h9c3ff4c_0    conda-forge
libcurl                   8.1.2                h409715c_0    conda-forge
libdeflate                1.8                  h7f8727e_5    anaconda
libecpint                 1.0.7                hfebba4c_0    psi4
libedit                   3.1.20221030         h5eee18b_0    anaconda
libev                     4.33                 h7f8727e_1    anaconda
libevent                  2.1.10               h28343ad_4    conda-forge
libffi                    3.4.2                h6a678d5_6    anaconda
libgcc-ng                 13.2.0               h807b86a_1    conda-forge
libgfortran-ng            7.5.0               ha8ba4b0_17    anaconda
libgfortran4              7.5.0               ha8ba4b0_17    anaconda
libgomp                   13.2.0               h807b86a_1    conda-forge
libgoogle-cloud           2.7.0                h21dfe5b_1    conda-forge
libgrpc                   1.51.1               h4fad500_1    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libint2                   2.7.1               h2fe1556_15    psi4
liblapack                 3.9.0            12_linux64_mkl    conda-forge
libnetcdf                 4.7.4           nompi_h56d31a8_107    conda-forge
libnghttp2                1.52.0               h61bc06f_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libpng                    1.6.37               hbc83047_0    anaconda
libpq                     15.2                 hb675445_0    conda-forge
libprotobuf               3.21.12              hfc55251_2    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libsqlite                 3.43.0               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_1    conda-forge
libthrift                 0.18.0               h5e4af38_0    conda-forge
libtiff                   4.5.0                h6a678d5_1    anaconda
libutf8proc               2.8.0                h166bdaf_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp                   1.2.4                h11a3e52_0    anaconda
libwebp-base              1.2.4                h5eee18b_0    anaconda
libxc                     5.1.5                h84b9e52_1    psi4
libxcb                    1.15                 h7f8727e_0    anaconda
libxml2                   2.10.3               hca2bb57_4    conda-forge
libzip                    1.10.1               h2629f0a_3    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lz4                       4.3.2            py39h724f13c_0    conda-forge
lz4-c                     1.9.4                h6a678d5_0    anaconda
lzo                       2.10              h516909a_1000    conda-forge
mako                      1.2.3            py39h06a4308_0    anaconda
markupsafe                2.1.1            py39h7f8727e_0    anaconda
matplotlib-base           3.6.2            py39h945d387_0    anaconda
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mda-xdrlib                0.2.0              pyhd8ed1ab_0    conda-forge
mdanalysis                2.6.1            py39h26d5377_0    conda-forge
mdtraj                    1.9.9            py39h031bd0f_0    conda-forge
mistune                   3.0.1              pyhd8ed1ab_0    conda-forge
mkl                       2021.4.0           h06a4308_640    anaconda
mkl-service               2.4.0            py39h7f8727e_0    anaconda
mkl_fft                   1.3.1            py39hd3c417c_0    anaconda
mkl_random                1.2.2            py39h51133e4_0    anaconda
mmpbsa-py                 16.0                     pypi_0    pypi
mmtf-python               1.1.3              pyhd8ed1ab_0    conda-forge
mock                      5.1.0              pyhd8ed1ab_0    conda-forge
mrcfile                   1.4.3              pyhd8ed1ab_0    conda-forge
msgpack-python            1.0.3            py39hd09550d_0    anaconda
munkres                   1.1.4                      py_0    anaconda
nbclient                  0.8.0              pyhd8ed1ab_0    conda-forge
nbconvert-core            7.8.0              pyhd8ed1ab_0    conda-forge
nbformat                  5.9.2              pyhd8ed1ab_0    conda-forge
ncurses                   6.4                  h6a678d5_0    anaconda
nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
netcdf-fortran            4.5.3           nompi_hfef6a68_101    conda-forge
netcdf4                   1.5.6           nompi_py39h36800e2_102    conda-forge
networkx                  2.8.4            py39h06a4308_0    anaconda
notebook                  7.0.3              pyhd8ed1ab_0    conda-forge
notebook-shim             0.2.3              pyhd8ed1ab_0    conda-forge
numexpr                   2.8.4            py39he184ba9_0    anaconda
numpy                     1.22.3           py39he7a7128_0    anaconda
numpy-base                1.22.3           py39hf524024_0    anaconda
ocl-icd                   2.3.1                h7f98852_0    conda-forge
ocl-icd-system            1.0.0                         1    conda-forge
openbabel                 3.1.1            py39h80c93ca_5    conda-forge
openff-amber-ff-ports     0.0.3              pyh6c4a22f_0    conda-forge
openff-forcefields        2023.08.0          pyh1a96a4e_0    conda-forge
openff-interchange        0.2.3              pyhd8ed1ab_1    conda-forge
openff-interchange-base   0.2.3              pyhd8ed1ab_1    conda-forge
openff-toolkit            0.12.1             pyhd8ed1ab_2    conda-forge
openff-toolkit-base       0.12.1             pyhd8ed1ab_2    conda-forge
openff-units              0.2.1              pyh1a96a4e_0    conda-forge
openff-utilities          0.1.9              pyh1a96a4e_0    conda-forge
openmm                    8.0.0            py39h7d85326_1    conda-forge
openssl                   3.1.3                hd590300_0    conda-forge
optking                   0.2.1              pyhbc12335_1    psi4
orc                       1.8.2                hfdbbad2_2    conda-forge
overrides                 7.4.0              pyhd8ed1ab_0    conda-forge
packaging                 22.0             py39h06a4308_0    anaconda
packmol-memgen            1.1.0rc0                 pypi_0    pypi
pandas                    1.4.4            py39h6a678d5_0    anaconda
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
panedr                    0.7.2              pyhd8ed1ab_0    conda-forge
parmed                    at20RC5+54.g5702a232fe.dirty          pypi_0    pypi
parquet-cpp               1.5.1                         2    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
partd                     1.4.0              pyhd8ed1ab_1    conda-forge
patsy                     0.5.3              pyhd8ed1ab_0    conda-forge
pbr                       5.11.1             pyhd8ed1ab_0    conda-forge
pcmsolver                 1.2.1.1          py39h92d4acf_3    psi4
pcre                      8.45                 h295c915_0    anaconda
pdb4amber                 1.7.dev0                 pypi_0    pypi
perl                      5.32.1          4_hd590300_perl5    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.3.0            py39h6a678d5_2    anaconda
pint                      0.21               pyhd8ed1ab_0    conda-forge
pip                       22.3.1           py39h06a4308_0    anaconda
pixman                    0.40.0               h7f8727e_1    anaconda
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
platformdirs              3.1.1              pyhd8ed1ab_0    conda-forge
plotly                    5.9.0            py39h06a4308_0    anaconda
pluggy                    1.0.0            py39h06a4308_1    anaconda
postgresql                15.2                 h3248436_0    conda-forge
prometheus_client         0.17.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.39             pyha770c72_0    conda-forge
prompt_toolkit            3.0.39               hd8ed1ab_0    conda-forge
psi4                      1.6.1+5b9f6e3    py39h1bd450f_0    psi4
psiresp                   0.4.2              pyhd8ed1ab_0    conda-forge
psiresp-base              0.4.2              pyhd8ed1ab_0    conda-forge
psutil                    5.9.0            py39h5eee18b_0    anaconda
psycopg2                  2.9.3            py39h24a400a_2    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
py                        1.11.0             pyhd3eb1b0_0    anaconda
py-cpuinfo                8.0.0              pyhd3eb1b0_1    anaconda
pyarrow                   11.0.0          py39hf0ef2fd_5_cpu    conda-forge
pycairo                   1.21.0           py39h287db57_0    anaconda
pycparser                 2.21               pyhd3eb1b0_0    anaconda
pydantic                  1.10.2           py39h5eee18b_0    anaconda
pyedr                     0.7.2              pyhd8ed1ab_0    conda-forge
pygments                  2.16.1             pyhd8ed1ab_0    conda-forge
pyopenssl                 23.2.0             pyhd8ed1ab_1    conda-forge
pyparsing                 3.0.9            py39h06a4308_0    anaconda
pyrsistent                0.19.3           py39h72bdee0_0    conda-forge
pysocks                   1.7.1            py39h06a4308_0    anaconda
pytables                  3.6.1            py39hf6dc253_3    conda-forge
pytest                    7.1.2            py39h06a4308_0    anaconda
python                    3.9.16          h2782a2a_0_cpython    conda-forge
python-constraint         1.4.0                      py_0    conda-forge
python-dateutil           2.8.2              pyhd3eb1b0_0    anaconda
python-fastjsonschema     2.18.0             pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytng                     0.3.0            py39h0050040_0    conda-forge
pytraj                    2.0.5                    pypi_0    pypi
pytz                      2022.7           py39h06a4308_0    anaconda
pyyaml                    6.0              py39h5eee18b_1    anaconda
pyzmq                     25.1.1           py39hb257651_0    conda-forge
qcelemental               0.25.1             pyhd8ed1ab_1    psi4
qcengine                  0.24.1             pyhd8ed1ab_0    psi4
qcfractal                 0.15.8.1         py39hf3d152e_1    conda-forge
qcfractal-core            0.15.8.1         py39hf3d152e_1    conda-forge
rdkit                     2022.09.1        py39h79face8_0    conda-forge
re2                       2023.02.01           hcb278e6_0    conda-forge
readline                  8.2                  h5eee18b_0    anaconda
reportlab                 3.5.67           py39hfdd840d_1    anaconda
requests                  2.28.1           py39h06a4308_0    anaconda
rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
s2n                       1.3.37               h3358134_0    conda-forge
sander                    16.0                     pypi_0    pypi
scikit-learn              1.3.0            py39hc236052_0    conda-forge
scipy                     1.7.3            py39hc147768_0    anaconda
seaborn                   0.12.2               hd8ed1ab_0    conda-forge
seaborn-base              0.12.2             pyhd8ed1ab_0    conda-forge
send2trash                1.8.2              pyh41d4057_0    conda-forge
setuptools                65.6.3           py39h06a4308_0    anaconda
simint                    0.7                  h642920c_1    psi4
six                       1.16.0             pyhd3eb1b0_1    anaconda
smirnoff99frosst          1.1.0              pyh44b312d_0    conda-forge
snappy                    1.1.9                h295c915_0    anaconda
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.5                pyhd8ed1ab_1    conda-forge
sqlalchemy                1.3.23           py39h27cfd23_0    anaconda
sqlite                    3.40.1               h5082296_0    anaconda
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
statsmodels               0.14.0           py39h0f8d45d_1    conda-forge
tblib                     2.0.0              pyhd8ed1ab_0    conda-forge
tenacity                  8.0.1            py39h06a4308_1    anaconda
terminado                 0.17.1             pyh41d4057_0    conda-forge
threadpoolctl             3.2.0              pyha21a80b_0    conda-forge
tidynamics                1.1.2              pyhd8ed1ab_0    conda-forge
tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h1ccaba5_0    anaconda
tomli                     2.0.1            py39h06a4308_0    anaconda
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.2              py39h5eee18b_0    anaconda
tqdm                      4.64.1           py39h06a4308_0    anaconda
traitlets                 5.10.0             pyhd8ed1ab_0    conda-forge
typing-extensions         4.4.0            py39h06a4308_0    anaconda
typing_extensions         4.4.0            py39h06a4308_0    anaconda
typing_utils              0.1.0              pyhd8ed1ab_0    conda-forge
tzcode                    2023c                h0b41bf4_0    conda-forge
tzdata                    2022a                hda174b7_0    anaconda
uri-template              1.3.0              pyhd8ed1ab_0    conda-forge
urllib3                   1.26.14          py39h06a4308_0    anaconda
utf8proc                  2.6.1                h27cfd23_0    anaconda
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
webcolors                 1.13               pyhd8ed1ab_0    conda-forge
webencodings              0.5.1              pyhd8ed1ab_2    conda-forge
websocket-client          1.6.3              pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd3eb1b0_0    anaconda
widgetsnbextension        3.6.6              pyhd8ed1ab_0    conda-forge
xmltodict                 0.13.0             pyhd8ed1ab_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.8.6                h8ee46fc_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxt                1.3.0                hd590300_0    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xyzservices               2023.7.0           pyhd8ed1ab_0    conda-forge
xz                        5.2.10               h5eee18b_1    anaconda
yaml                      0.2.5                h7b6447c_0    anaconda
zeromq                    4.3.4                h9c3ff4c_1    conda-forge
zict                      3.0.0              pyhd8ed1ab_0    conda-forge
zipp                      3.11.0           py39h06a4308_0    anaconda
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.2                ha4553b6_0    anaconda

```

**Comment by zd9999cs** [comment]
I found out that set keep_original_conformer  to False helps the program to proceed

**Comment by lilyminium** [comment]
Thanks for raising this issue @zd9999cs and for looking into it further! Unfortunately I've been at the MDAnalysis UGM the past few days but I'll get to this as soon as I can.
